plotwist-app/plotwist

- .gitignore
- Dockerfile
- docker-compose.yml
This PR aim's to add the project dockerfile.
> build: add the project's dockerfile

- src/app/app/components/poster.tsx
- src/app/app/components/sidebar-search-person.tsx
- src/app/app/movies/[id]/components/movie-credits.tsx
- src/app/app/movies/[id]/components/movie-details-providers-item.tsx
- src/app/app/movies/[id]/components/movie-images.tsx
- src/components/tv-show-card.tsx
This PR want to remove some console warnings and change the image loading method
> chore: add props into image tags

- src/app/[lang]/tv-series/[id]/_components/tv-serie-season-episode-card.tsx
- src/app/[lang]/tv-series/[id]/_components/tv-serie-seasons.tsx
- src/components/movie-card/movie-card.tsx
- src/components/tv-serie-card/tv-show-card.tsx
This PR fix #80
This PR includes: 
- Prevent empty images at movie and tv-series card's
- Prevent empty images at season episode
> feat(tv-series): implement conditional rendering for Image component

- .vscode/settings.json
- apps/web/public/dictionaries/de-DE.json
- apps/web/public/dictionaries/en-US.json
- apps/web/public/dictionaries/es-ES.json
- apps/web/public/dictionaries/fr-FR.json
- apps/web/public/dictionaries/it-IT.json
- apps/web/public/dictionaries/ja-JP.json
- apps/web/public/dictionaries/pt-BR.json
- apps/web/src/components/full-review/full-review.tsx
- apps/web/src/components/reviews/review-likes/review-likes.tsx
- apps/web/src/services/api/profiles/get-profiles-by-id.ts
- apps/web/src/utils/dictionaries/get-dictionaries.types.ts
- package.json
- pnpm-lock.yaml
> feat: add modal of users who liked the review

- apps/web/src/app/[lang]/[username]/_components/profile-form.tsx
- apps/web/src/app/[lang]/lists/[id]/_components/list-items/list-item-actions.tsx
- apps/web/src/app/[lang]/people/[id]/components/data-table/data-table.tsx
- apps/web/src/components/ui/calendar.tsx
- apps/web/src/components/ui/radio-group.tsx
- pnpm-lock.yaml
This pull request fixes the Edit Profile modal which translations were not added on the component.
There's no issue to this PR.
> fix(profile-form): modal translations added

- package.json
- pnpm-lock.yaml
> Remove packageManager setting from package json

- apps/web/src/middleware.ts
> Set location by browser option

- apps/web/src/components/ui/input.tsx
- apps/web/src/components/ui/textarea.tsx
Changes input component font size from `text-sm` to `text-base`.
#161 - Fixes PLO-48
> Change text fields font size

- apps/web/src/app/[lang]/thank-you/page.tsx
> feat:add pro links navigation

- apps/web/public/dictionaries/de-DE.json
- apps/web/public/dictionaries/en-US.json
- apps/web/public/dictionaries/es-ES.json
- apps/web/public/dictionaries/fr-FR.json
- apps/web/public/dictionaries/it-IT.json
- apps/web/public/dictionaries/ja-JP.json
- apps/web/public/dictionaries/pt-BR.json
- apps/web/src/app/[lang]/[username]/_components/profile-lists.tsx
- apps/web/src/components/list-card/list-card.tsx
- apps/web/src/utils/dictionaries/get-dictionaries.types.ts
- package.json
- pnpm-lock.yaml
in this Pull request just added a message for a profile page that dont have any lists yet, when the user is seeing another profile page and dont have any list show a message box "this user still dont have any list"
PLO-28
[#128](https://github.com/plotwist-app/plotwist/issues/128)
- A message box that is displayed if the user is viewing another profile without lists.
-Preview:
> feat: no list message

- apps/web/src/app/[lang]/_components/__tests__/popular-reviews.test.tsx
- apps/web/src/app/[lang]/_components/popular-reviews.tsx
- apps/web/src/components/full-review/full-review.tsx
Created a small integration test suite for the `popular-reviews` component. The suite contains 3 simple tests where: 
- It asserts the date range filters (last week/last month/all time) are rendered correctly.
- It asserts that the list gets rendered correctly - I'm intentionally not test how the single review renders as, ideally, this would be a test for the `full-review` component.
- It asserts that the empty state is rendered correctly when no reviews are found.
My intention was to get to know the codebase while doing something meaningful as a contribution. Feel free to throw as many comments as might see fit. I might not be following whatever best practices you have on the project, happy to change anything if needed 😅.
> Test: adds popular-reviews integration test suite

- .github/ci.yml
- package.json
- turbo.json
This PR will create a Github workflow to that will run tests on every pull request, ensuring that code changes won't break production code.
The action workflow will only run tests for now, but it can be expanded to do more stuff, like linting or any build related command.
> chore: adds GH action workflow

- apps/web/src/components/header/header.tsx
A register button has been added to the header so that the user can register or log in from any page on the site.
PLO-62
#190
a register button in header
preview:
> feat: add button signup in header

- apps/web/src/components/reviews/review-likes/review-likes.tsx
- apps/web/src/services/api/likes/get-likes.ts
- pnpm-lock.yaml
Optimization of requests performed by reducing them from two to one through the use of join to pull user information alongside the number of likes
Optimization of requests about likes behavior
> improvement: optimized ReviewLikes request

- apps/web/src/components/tv-series-list-filters/tabs/filters/(fields)/genres.tsx
- pnpm-lock.yaml
Change CommandPrimitive.Input to CommandInput and CommandGroup to CommandList in order to fix Unhandled Runtime Error TypeError: undefined is not iterable (cannot read property of Symbole(Symbole.iterator))
#219
> Bug/tv-series filter issues(use CommandInput and CommandList)

- apps/web/src/components/logo/logo.tsx
- apps/web/src/middleware.ts
- apps/web/src/services/api/users/get-user.ts
This PR fixes the issue where authenticated users are redirected to the homepage when clicking on the header. Now, clicking the header will redirect authenticated users to the Home page, where the appropriate content is available.
Updated the redirection behavior in the header for authenticated users.
Ensured that the redirection correctly leads to the Home page.
Updated the middleware to ensure that authenticated users cannot access the inital page.
Log in to the application as an authenticated user.
Click on the header.
Verify that the redirection leads to the Home page.
> Fix(header): Redirect Authenticated Users to Home Page Instead of Initial Page

- apps/web/public/dictionaries/de-DE.json
- apps/web/public/dictionaries/en-US.json
- apps/web/public/dictionaries/es-ES.json
- apps/web/public/dictionaries/fr-FR.json
- apps/web/public/dictionaries/it-IT.json
- apps/web/public/dictionaries/ja-JP.json
- apps/web/public/dictionaries/pt-BR.json
- apps/web/src/app/[lang]/_components/hero.tsx
- apps/web/src/components/pricing/pricing.tsx
Fix [PLO-134](https://linear.app/plotwist/issue/PLO-134/bug-it-is-possible-to-create-an-account-while-logged-in)
> fix: prevent sign-up w/ active session

- apps/web/src/app/[lang]/_components/hero.tsx
- pnpm-lock.yaml
- Implemented smooth scrolling when navigating to sections via links in the hero section.
- Enhanced user experience with a seamless transition effect between sections.
https://github.com/user-attachments/assets/f3ddbe3b-991c-4a7a-9524-ecf6b699b604
> style: add smooth scroll behavior on hero section links

- apps/web/src/app/[lang]/sign-in/_sign-in-form.tsx
- apps/web/src/app/[lang]/sign-in/page.tsx
- apps/web/src/app/[lang]/sign-up/page.tsx
- apps/web/src/components/animated-link/animated-link.tsx
Reverts plotwist-app/plotwist#295
> Revert "style: re-add old auth layout pattern"

- apps/web/src/components/reviews/review-form/review-form.tsx
> feat:  update user item status after review submission

- apps/web/src/components/reviews/review-form/review-form.tsx
- pnpm-lock.yaml
This pull request includes a change to the `ReviewForm` component in the `review-form.tsx` file. The change ensures that the form is reset with specific default values after a successful submission.
* [`apps/web/src/components/reviews/review-form/review-form.tsx`](diffhunk://#diff-801737340ad8b770d570d54b3b6c17308251e436a858d49ab31ea0f1ee732904L130-R134): Modified the `form.reset` method to reset the `review`, `rating`, and `hasSpoilers` fields to their default values after a successful form submission.
Original Issue: [Bug: When submitting a review, the nº of stars remains for the next review.](https://github.com/plotwist-app/plotwist/issues/316)
https://github.com/user-attachments/assets/afa8839c-e0d9-44ef-b5b5-73056b1946de
> fix(apps/web): forcing form reset with fixed params

- apps/web/src/components/item-review/index.tsx
This pull request includes changes to the ItemReviewContent component in the apps/web/src/components/item-review/index.tsx file to improve the visual feedback for the review button. The most important changes include importing a utility function and modifying the Star component to conditionally fill and style based on the review state.
Improvements to visual feedback:
[apps/web/src/components/item-review/index.tsx](https://github.com/plotwist-app/plotwist/compare/task/PLO-165?expand=1): Added import for cn utility function from @/lib/utils.
[apps/web/src/components/item-review/index.tsx](https://github.com/plotwist-app/plotwist/compare/task/PLO-165?expand=1): Modified the Star component to conditionally fill with yellow and apply a text-yellow-500 class if a review exists. …
> feat: update start icon to be yellowish and filled when item is already reviewe

- apps/web/src/components/logo/logo.tsx
This pull request updates the Logo component in the apps/web/src/components/logo/logo.tsx file to use the useSession hook. The Logo link URL is conditionally set depending on the user's authentication status. If the user is logged in, they are directed to the /home page; if not, they are sent to the landing page (/).
https://github.com/plotwist-app/plotwist/issues/360
> fix: update logo href to home if user is authenticated

- apps/web/src/app/[lang]/[username]/_components/user-activity.tsx
This pull request updates the UserActivity component to include both date and time in the tooltip content for enhanced clarity.
`apps/web/src/app/[lang]/[username]/_components/user-activity.tsx`:
Updated the date formatting in TooltipContent to display both the date and time.
(See [line 243](https://github.com/plotwist-app/plotwist/compare/task/PLO-176?expand=1))
https://github.com/plotwist-app/plotwist/issues/371
> perf: update date-fns format do include time

- apps/web/public/dictionaries/de-DE.json
- apps/web/public/dictionaries/en-US.json
- apps/web/public/dictionaries/es-ES.json
- apps/web/public/dictionaries/fr-FR.json
- apps/web/public/dictionaries/it-IT.json
- apps/web/public/dictionaries/ja-JP.json
- apps/web/public/dictionaries/pt-BR.json
- apps/web/src/api/auth.ts
- apps/web/src/api/endpoints.schemas.ts
- apps/web/src/api/users.ts
- apps/web/src/components/command-search/command-search-items.tsx
- apps/web/src/components/command-search/command-search.tsx
> feat: Search users

- apps/web/public/dictionaries/de-DE.json
- apps/web/public/dictionaries/en-US.json
- apps/web/public/dictionaries/es-ES.json
- apps/web/public/dictionaries/fr-FR.json
- apps/web/public/dictionaries/it-IT.json
- apps/web/public/dictionaries/ja-JP.json
- apps/web/public/dictionaries/pt-BR.json
- apps/web/src/app/[lang]/tv-series/[id]/_components/tv-series-progress.tsx
> feat: add progress completed localization and update button text
